:pygments-style: tango
:source-highlighter: pygments
:toc:
:toclevels: 7
:sectnums:
:sectnumlevels: 6
:numbered:
:chapter-label:
:icons: font
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images/


=== Defining Software Defined Networks

This section presents the reasoning why OpenShift Container Platform depends on Software-Defined Networks and what they are.

==== Why using Software-Defined Networks in a cloud environment?

Software-defined networks enable dynamic and programmatic network configuration in order to improve network performance and monitoring. 

It is a different approach than addressing static architecture of traditional networks and may be employed to centralize network intelligence in one network component by disassociating the forwarding process of network packets (data plane) from the routing process (control plane).

It relies on a OpenFlow protocol to manage network devices and all packages transported by them.

===== SDN Control Plane

The implementation of a SDN control plane might be centralized, hierarchical, or distributed. 

A centralized solution, where a single control entity has a global view of the network, simplifies the implementation of the control logic, it has scalability limitations as the size and dynamics of the network increase. 

A hierarchical solution distributes controllers to operate on a partitioned network view, while decisions that require network-wide knowledge are taken by a logically centralized root controller. 

In distributed approaches, controllers operate on their local view or they may exchange synchronization messages to enhance their knowledge. Distributed solutions are more suitable for supporting adaptive SDN applications.

===== SDN Data Plane

The data plane is responsible for processing data-carrying packets using a set of rules specified by the control plane. The data plane may be implemented in physical hardware switches or in software implementations, such as Open vSwitch. The memory capacity of hardware switches may limit the number of rules that can be stored where as software implementations may have higher capacity.


==== OpenShift and the software defined network

OpenShift supports multiple SDN plugins to support specific use cases. 

If not explicitely defined, OpenShift deploys the OVN-Kubernetes SDN plugin.  Alternatively, it also provides OpenShift SDN plugin that was used in previous versions of OpenShift and it provides backward compatibility to old clusters. 

[IMPORTANT]
====
These plugins must be configured during the installation of OpenShift! No changes can be done afterwards.
====

On the top of these SDN implementations, there are other extensions that supports internal network operations like:

. DNS server (OpenDNS)
. Load balancers in a bare metal environment (MetalLB)
. Encrypted web traffic (Ingress Controller).

If you need to address multiple SDN plugins, you need to use Multus plugin.


Among others that are described in this link:

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/networking/networking-operators-overview


Comparing two major SDN implementations used in OpenShift:

[Default CNI network provider feature comparison]
|===
|Feature    |OVN-Kubernetes |OpenShift SDN
|Egress IPs |Supported   |Supported
|Egress firewall|Supported |Supported
|Egress router |Supported |Supported
|IPsec encryption| Supported |Not supported
|IPv6|Supported |Not supported
|Kubernetes network policy |Supported |Partially supported
|Kubernetes network policy logs |Supported |Not supported
|Multicast |Supported |Supported
|===

However OVN-Kubernetes has some limitations:

. In a dual stack network (IPv4/IPv6) must use the same network device as their gateway.
. As a side effect, both network stacks must configure routing tables with the default gateway.
. Session stickyness uses the last request as the initial moment to timeout stickyness.

