# Workflow name
name: Build PDF


# Controls when the workflow will run
on: 
  # This is a reusable workflow
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:

      # In this job, all steps begin with a name
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Podman Build Book
        run: bash ./adocpdf.sh Main.adoc

      - name: Podman Build Book
        run: podman run --name adocpdf --rm  -e "pdf-theme=/opt/asciidoc/themes/tm-gls-redhat-theme.yml" -e "book_name=Main.adoc" -v $(pwd):/tmp/coursebook:Z quay.io/tmichett/asciidocpdf:latest

      - name: Commit and Add Book
        run: git config --global user.email "jtaniguc@redhat.com" && git config --global user.name "Ricardo Taniguchi" && git add Main.pdf && git commit -m "Added new main.pdf" && git push
